Repository ultralytics/yolov5, pull requests merged in 2022-09, with the labels that each got.

#9493 Segmentation `polygons2masks_overlap()` in `np.int32`
  utils/segment/dataloaders.py
Labels: TODO

#9542 Add `--source screen` for screenshot inference
  README.md
  classify/predict.py
  detect.py
  requirements.txt
  segment/predict.py
  tutorial.ipynb
  utils/dataloaders.py
Labels: enhancement, TODO

#9228 Detect.py supports running against a Triton container
  classify/predict.py
  detect.py
  models/common.py
  requirements.txt
  segment/predict.py
  utils/downloads.py
  utils/triton.py
Labels: enhancement

#9571 Add segment line predictions
  segment/predict.py
  utils/segment/general.py
Labels: enhancement, TODO

#9581 TensorRT detect.py inference fix
  .github/workflows/ci-testing.yml
  classify/predict.py
  detect.py
  segment/predict.py
Labels: bug, TODO
