Repository ultralytics/yolov5, pull requests merged in 2024-10, with the labels that each got.

#13344 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
  README.zh-CN.md
  utils/loggers/clearml/README.md
Labels: documentation

#13345 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
  README.zh-CN.md
Labels: documentation, enhancement

#13353 Update codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement, dependencies

#13361 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/cla.yml
  .github/workflows/format.yml
  .github/workflows/merge-main-into-prs.yml
Labels: enhancement, python

#13355 Fix bug when enable `--quad` training option
  utils/dataloaders.py
  utils/segment/dataloaders.py
Labels: bug, python

#13365 Update Integrations table
  README.md
  README.zh-CN.md
Labels: documentation, enhancement

#13366 Update README.md
  README.md
  README.zh-CN.md
Labels: documentation

#13368 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
  README.md
  README.zh-CN.md
  classify/tutorial.ipynb
  data/coco128-seg.yaml
  data/coco128.yaml
  segment/tutorial.ipynb
  tutorial.ipynb
Labels: documentation, enhancement, python

#13374 Update README.md with YOLO11 section
  README.md
  README.zh-CN.md
Labels: documentation, enhancement
