Repository ultralytics/yolov5, pull requests merged in 2024-09, with the labels that each got.

#13289 PyUpgrade 3.8 updates
  classify/predict.py
  detect.py
  segment/predict.py
  utils/metrics.py
Labels: documentation

#13301 Ultralytics Code Refactor https://ultralytics.com/actions
  CONTRIBUTING.md
  README.md
  README.zh-CN.md
  export.py
  utils/flask_rest_api/README.md
  utils/loggers/clearml/README.md
Labels: documentation, enhancement, python

#13309 Delete .github/workflows/greetings.yml
  .github/workflows/format.yml
  .github/workflows/greetings.yml
Labels: enhancement
