Repository ultralytics/yolov5, pull requests merged in 2024-08, with the labels that each got.

#13236 Replace ONNXSim with ONNXSlim
  export.py
Labels: enhancement, dependencies, python

#13260 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: enhancement, dependencies

#13261 YOLO Vision 2024 updates https://ultralytics.com/events/yolovision
  .github/workflows/format.yml
  README.md
  README.zh-CN.md
Labels: enhancement, python

#13268 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
  README.zh-CN.md
  classify/tutorial.ipynb
  segment/tutorial.ipynb
Labels: documentation, enhancement

#13270 Remove Hindi links
  tutorial.ipynb
Labels: documentation

#13272 Provide option for saving box coordinates in Pascal-VOC format.
  detect.py
Labels: enhancement, python

#13278 Apply Ruff Docstring reformat
  export.py
  utils/augmentations.py
  utils/callbacks.py
  utils/dataloaders.py
  utils/general.py
  utils/loggers/__init__.py
  utils/loggers/clearml/clearml_utils.py
  utils/loggers/wandb/wandb_utils.py
  utils/metrics.py
  utils/segment/augmentations.py
  utils/segment/general.py
  utils/triton.py
Labels: documentation, python

#13282 Update merge-main-into-prs.yml
  .github/workflows/merge-main-into-prs.yml
Labels: enhancement, python

#13283 Update README.md
  export.py
  hubconf.py
  models/tf.py
  segment/val.py
  utils/dataloaders.py
  utils/loggers/__init__.py
  utils/loggers/clearml/clearml_utils.py
  utils/loggers/wandb/wandb_utils.py
  utils/loss.py
  utils/metrics.py
  utils/plots.py
  utils/segment/general.py
  utils/segment/metrics.py
  utils/torch_utils.py
  utils/triton.py
Labels: documentation

#13284 Add https://www.reddit.com/r/Ultralytics/ badge
  .github/workflows/merge-main-into-prs.yml
  README.md
  README.zh-CN.md
  export.py
  models/common.py
  models/tf.py
  models/yolo.py
  utils/__init__.py
  utils/activations.py
  utils/augmentations.py
  utils/dataloaders.py
  utils/general.py
  utils/loggers/__init__.py
  utils/loss.py
  utils/metrics.py
  utils/plots.py
  utils/segment/dataloaders.py
  utils/segment/loss.py
  utils/segment/metrics.py
  utils/torch_utils.py
Labels: documentation, enhancement

#13285 Fix YOLOv8 links
  README.md
  README.zh-CN.md
Labels: documentation
