Repository ultralytics/yolov5, pull requests merged in 2024-11, with the labels that each got.

#13403 Fix PyPI downloads links
  README.md
  README.zh-CN.md
Labels: documentation

#13406 Use new Ultralytics Retry action
  .github/workflows/links.yml
Labels: enhancement, devops

#13407 Use new Ultralytics Retry action
  .github/workflows/links.yml
Labels: enhancement, devops

#13408 Fix URL
  .github/workflows/format.yml
Labels: documentation

#13386 Add timing cache to accelerate consequent `.engine` export
  export.py
  train.py
Labels: documentation, enhancement

#13421 Update ci-testing.yml
  .github/workflows/ci-testing.yml
Labels: devops

#13426 Fix possible image drawing issues
  utils/plots.py
Labels: enhancement

#13431 Delete .github/workflows/codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: devops
