Repository ultralytics/yolov5, pull requests merged in 2025-03, with the labels that each got.

#13525 Fix potential memory leak for cache ram
  utils/dataloaders.py
Labels: bug, enhancement

#13542 Update GitHub banner redirect
  README.md
  README.zh-CN.md
  utils/loggers/clearml/README.md
  utils/loggers/comet/README.md
Labels: documentation

#13543 Update Python example
  README.md
  README.zh-CN.md
Labels: documentation

#13545 Update README.zh-CN.md
  README.zh-CN.md
Labels: documentation

#13546 Update Dockerfile headers
  utils/docker/Dockerfile
  utils/docker/Dockerfile-arm64
  utils/docker/Dockerfile-cpu
Labels: documentation, devops

#13548 Pin `paddlepaddle<3.0.0` to avoid bug in latest release
  export.py
  models/common.py
Labels: dependencies, exports

#13553 Ultralytics Refactor https://ultralytics.com/actions
  README.md
  data/scripts/download_weights.sh
  data/scripts/get_coco.sh
  data/scripts/get_coco128.sh
  data/scripts/get_imagenet.sh
  data/scripts/get_imagenet10.sh
  data/scripts/get_imagenet100.sh
  data/scripts/get_imagenet1000.sh
  utils/aws/mime.sh
  utils/aws/userdata.sh
  utils/flask_rest_api/README.md
  utils/loggers/clearml/README.md
  utils/loggers/comet/README.md
Labels: documentation, enhancement, python

#13554 Update YOLOv5 READMEs
  README.md
  README.zh-CN.md
  utils/flask_rest_api/README.md
  utils/loggers/clearml/README.md
  utils/loggers/comet/README.md
Labels: documentation

#13555 Update README.md
  README.md
  README.zh-CN.md
Labels: documentation
