Repository ultralytics/yolov5, pull requests merged in 2025-01, with the labels that each got.

#13479 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#13484 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#13486 Apply `ruff==0.9.0` formatting
  README.md
  README.zh-CN.md
  classify/predict.py
  classify/train.py
  detect.py
  export.py
  segment/predict.py
  segment/train.py
  train.py
  utils/augmentations.py
  utils/dataloaders.py
  utils/general.py
  utils/loggers/clearml/clearml_utils.py
  utils/loggers/comet/__init__.py
  utils/loggers/wandb/wandb_utils.py
  utils/loss.py
  utils/segment/augmentations.py
  utils/segment/dataloaders.py
  utils/segment/loss.py
  utils/torch_utils.py
Labels: documentation, enhancement

#13488 Fix TFLite Segment inference
  models/common.py
  utils/dataloaders.py
  utils/general.py
  utils/loggers/clearml/clearml_utils.py
  utils/torch_utils.py
Labels: bug, exports, segment

#13490 Standardize license headers in Python files
  benchmarks.py
  classify/predict.py
  classify/train.py
  classify/val.py
  detect.py
  export.py
  hubconf.py
  models/__init__.py
  models/common.py
  models/experimental.py
  models/tf.py
  models/yolo.py
  segment/predict.py
  segment/train.py
  segment/val.py
  train.py
  utils/__init__.py
  utils/activations.py
  utils/augmentations.py
  utils/autoanchor.py
  utils/autobatch.py
  utils/aws/__init__.py
  utils/aws/resume.py
  utils/callbacks.py
  utils/dataloaders.py
  utils/downloads.py
  utils/flask_rest_api/example_request.py
  utils/flask_rest_api/restapi.py
  utils/general.py
  utils/loggers/__init__.py
  utils/loggers/clearml/README.md
  utils/loggers/clearml/__init__.py
  utils/loggers/clearml/clearml_utils.py
  utils/loggers/clearml/hpo.py
  utils/loggers/comet/__init__.py
  utils/loggers/comet/comet_utils.py
  utils/loggers/comet/hpo.py
  utils/loggers/wandb/__init__.py
  utils/loggers/wandb/wandb_utils.py
  utils/loss.py
  utils/metrics.py
  utils/plots.py
  utils/segment/__init__.py
  utils/segment/augmentations.py
  utils/segment/dataloaders.py
  utils/segment/general.py
  utils/segment/loss.py
  utils/segment/metrics.py
  utils/segment/plots.py
  utils/torch_utils.py
  utils/triton.py
  val.py
Labels: documentation, devops

#13503 Update links.yml
  .github/workflows/links.yml
Labels: documentation, devops
